server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://8.129.213.16:3306/ry-vue?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 30
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
    database: 0
    host: 8.129.213.16
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
